apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-helm
spec:
  destination:
    namespace: $USER-bgdh
    server: 'https://kubernetes.default.svc'
  source:
    path: content/modules/ROOT/examples/bgd-helm-chart
    repoURL: 'https://github.com/OpenShiftDemos/openshift-gitops-workshop'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
